### ISSUE TITLE
Add I/O functions

### ISSUE THREAD

**Issue by madroach** [c-cube/ocaml-bigstring#4]
Hi,
would you mind adding those two functions to bigstring-unix? They need C stubs. Otherwise I would like to publish them as bigstring-io. https://github.com/inhabitedtype/bigstringaf/pull/34
I could prepare a pull-request, of course.
These are the functions I'd like to add:
``` ocaml
val read  : Unix.file_descr -> ?off:int -> ?len:int -> t -> int
val write : Unix.file_descr -> ?off:int -> ?len:int -> t -> int
```

**Comment by c-cube** [comment]
That sounds like a good idea, I'd appreciate a PR indeed.
